version: '3.9'

services:
  backend:
    container_name: 'kupipodariday-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-compose-kupipodariday
    env_file:
      - .env
    ports:
      - '4000:3000'
    networks:
      - internal
  frontend:
    container_name: 'kupipodariday-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-compose-kupipodariday
    ports:
      - '4001:80'
    networks:
      - external
  postgres:
    container_name: 'postgres'
    image: postgres:alpine
    env_file:
      - .env
    restart: always
    networks:
      - internal
    volumes:
      - pg-data:/data/postgress
  adminer:
    container_name: kupipodariday-adminer
    image: adminer
    ports:
      - 8081:8080
    restart: always
    networks:
      - internal
volumes:
  pg-data:
networks:
  internal:
  external:
