version: '3'

services:
  backend:
    container_name: 'kupipodariday-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-compose-kupipodariday
    env_file: ./backend/.env
    ports:
      - '4000:3000'
  postgres:
    container_name: 'postgres'
    image: postgres:alpine
    env_file: ./backend/.env
    restart: always
  frontend:
    container_name: 'kupipodariday-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-compose-kupipodariday
    ports:
      - '5000:80'
